/*     */ package org.mybatis.generator.plugins;
/*     */ 
/*     */ import java.util.ArrayList;
/*     */ import java.util.Date;
/*     */ import java.util.List;
/*     */ import java.util.Properties;
/*     */ import org.mybatis.generator.api.GeneratedXmlFile;
/*     */ import org.mybatis.generator.api.IntrospectedTable;
/*     */ import org.mybatis.generator.api.PluginAdapter;
/*     */ import org.mybatis.generator.api.dom.xml.Attribute;
/*     */ import org.mybatis.generator.api.dom.xml.Document;
/*     */ import org.mybatis.generator.api.dom.xml.TextElement;
/*     */ import org.mybatis.generator.api.dom.xml.XmlElement;
/*     */ import org.mybatis.generator.internal.util.StringUtility;
/*     */ import org.mybatis.generator.internal.util.messages.Messages;
/*     */ 
/*     */ public class MapperConfigPlugin extends PluginAdapter
/*     */ {
/*     */   private List<String> mapperFiles;
/*     */ 
/*     */   public MapperConfigPlugin()
/*     */   {
/*  60 */     this.mapperFiles = new ArrayList();
/*     */   }
/*     */ 
/*     */   public boolean validate(List<String> warnings) {
/*  64 */     boolean valid = true;
/*     */ 
/*  66 */     if (!StringUtility.stringHasValue(this.properties.getProperty("targetProject")))
/*     */     {
/*  68 */       warnings.add(Messages.getString("ValidationError.18", "MapperConfigPlugin", "targetProject"));
/*     */ 
/*  71 */       valid = false;
/*     */     }
/*     */ 
/*  74 */     if (!StringUtility.stringHasValue(this.properties.getProperty("targetPackage")))
/*     */     {
/*  76 */       warnings.add(Messages.getString("ValidationError.18", "MapperConfigPlugin", "targetPackage"));
/*     */ 
/*  79 */       valid = false;
/*     */     }
/*     */ 
/*  82 */     return valid;
/*     */   }
/*     */ 
/*     */   public List<GeneratedXmlFile> contextGenerateAdditionalXmlFiles()
/*     */   {
/*  87 */     Document document = new Document("-//mybatis.org//DTD Config 3.0//EN", "http://mybatis.org/dtd/mybatis-3-config.dtd");
/*     */ 
/*  91 */     XmlElement root = new XmlElement("configuration");
/*  92 */     document.setRootElement(root);
/*     */ 
/*  94 */     root.addElement(new TextElement("<!--"));
/*  95 */     root.addElement(new TextElement("  This file is generated by MyBatis Generator."));
/*     */ 
/*  97 */     root.addElement(new TextElement("  This file is the shell of a Mapper Config file - in many cases you will need to add"));
/*     */ 
/* 100 */     root.addElement(new TextElement("    to this file before it is usable by iBATIS."));
/*     */ 
/* 103 */     StringBuilder sb = new StringBuilder();
/* 104 */     sb.append("  This file was generated on ");
/* 105 */     sb.append(new Date());
/* 106 */     sb.append('.');
/* 107 */     root.addElement(new TextElement(sb.toString()));
/*     */ 
/* 109 */     root.addElement(new TextElement("-->"));
/*     */ 
/* 111 */     XmlElement mappers = new XmlElement("mappers");
/* 112 */     root.addElement(mappers);
/*     */ 
/* 115 */     for (String mapperFile : this.mapperFiles) {
/* 116 */       XmlElement mapper = new XmlElement("mapper");
/* 117 */       mapper.addAttribute(new Attribute("resource", mapperFile));
/* 118 */       mappers.addElement(mapper);
/*     */     }
/*     */ 
/* 121 */     GeneratedXmlFile gxf = new GeneratedXmlFile(document, this.properties.getProperty("fileName", "MapperConfig.xml"), this.properties.getProperty("targetPackage"), this.properties.getProperty("targetProject"), false);
/*     */ 
/* 127 */     List answer = new ArrayList(1);
/* 128 */     answer.add(gxf);
/*     */ 
/* 130 */     return answer;
/*     */   }
/*     */ 
/*     */   public boolean sqlMapGenerated(GeneratedXmlFile sqlMap, IntrospectedTable introspectedTable)
/*     */   {
/* 140 */     StringBuilder sb = new StringBuilder();
/* 141 */     sb.append(sqlMap.getTargetPackage());
/* 142 */     sb.append('.');
/* 143 */     String temp = sb.toString();
/* 144 */     sb.setLength(0);
/* 145 */     sb.append(temp.replace('.', '/'));
/* 146 */     sb.append(sqlMap.getFileName());
/* 147 */     this.mapperFiles.add(sb.toString());
/*     */ 
/* 149 */     return true;
/*     */   }
/*     */ }

/* Location:           C:\Users\sipingsoft-LILU.LJH\Desktop\mybatis-generator-core-1.3.0.jar
 * Qualified Name:     org.mybatis.generator.plugins.MapperConfigPlugin
 * JD-Core Version:    0.6.0
 */