/*     */ package org.mybatis.generator.internal;
/*     */ 
/*     */ import java.util.Date;
/*     */ import java.util.List;
/*     */ import java.util.Properties;
/*     */ import org.mybatis.generator.api.CommentGenerator;
/*     */ import org.mybatis.generator.api.IntrospectedColumn;
/*     */ import org.mybatis.generator.api.IntrospectedTable;
/*     */ import org.mybatis.generator.api.dom.java.CompilationUnit;
/*     */ import org.mybatis.generator.api.dom.java.Field;
/*     */ import org.mybatis.generator.api.dom.java.InnerClass;
/*     */ import org.mybatis.generator.api.dom.java.InnerEnum;
/*     */ import org.mybatis.generator.api.dom.java.JavaElement;
/*     */ import org.mybatis.generator.api.dom.java.Method;
/*     */ import org.mybatis.generator.api.dom.java.Parameter;
/*     */ import org.mybatis.generator.api.dom.xml.TextElement;
/*     */ import org.mybatis.generator.api.dom.xml.XmlElement;
/*     */ import org.mybatis.generator.internal.util.StringUtility;
/*     */ 
/*     */ public class DefaultCommentGenerator
/*     */   implements CommentGenerator
/*     */ {
/*     */   private Properties properties;
/*     */   private boolean suppressDate;
/*     */ 
/*     */   public DefaultCommentGenerator()
/*     */   {
/*  49 */     this.properties = new Properties();
/*  50 */     this.suppressDate = false;
/*     */   }
/*     */ 
/*     */   public void addJavaFileComment(CompilationUnit compilationUnit)
/*     */   {
/*     */   }
/*     */ 
/*     */   public void addComment(XmlElement xmlElement)
/*     */   {
/*  63 */     xmlElement.addElement(new TextElement("<!--"));
/*     */ 
/*  65 */     StringBuilder sb = new StringBuilder();
/*  66 */     sb.append("  WARNING - ");
/*  67 */     sb.append("@mbggenerated");
/*  68 */     xmlElement.addElement(new TextElement(sb.toString()));
/*  69 */     xmlElement.addElement(new TextElement("  This element is automatically generated by MyBatis Generator, do not modify."));
/*     */ 
/*  73 */     String s = getDateString();
/*  74 */     if (s != null) {
/*  75 */       sb.setLength(0);
/*  76 */       sb.append("  This element was generated on ");
/*  77 */       sb.append(s);
/*  78 */       sb.append('.');
/*  79 */       xmlElement.addElement(new TextElement(sb.toString()));
/*     */     }
/*     */ 
/*  82 */     xmlElement.addElement(new TextElement("-->"));
/*     */   }
/*     */ 
/*     */   public void addRootComment(XmlElement rootElement)
/*     */   {
/*     */   }
/*     */ 
/*     */   public void addConfigurationProperties(Properties properties)
/*     */   {
/*  91 */     this.properties.putAll(properties);
/*     */ 
/*  93 */     this.suppressDate = StringUtility.isTrue(properties.getProperty("suppressDate"));
/*     */   }
/*     */ 
/*     */   protected void addJavadocTag(JavaElement javaElement, boolean markAsDoNotDelete)
/*     */   {
/* 108 */     javaElement.addJavaDocLine(" *");
/* 109 */     StringBuilder sb = new StringBuilder();
/* 110 */     sb.append(" * ");
/* 111 */     sb.append("@mbggenerated");
/* 112 */     if (markAsDoNotDelete) {
/* 113 */       sb.append(" do_not_delete_during_merge");
/*     */     }
/* 115 */     String s = getDateString();
/* 116 */     if (s != null) {
/* 117 */       sb.append(' ');
/* 118 */       sb.append(s);
/*     */     }
/* 120 */     javaElement.addJavaDocLine(sb.toString());
/*     */   }
/*     */ 
/*     */   protected String getDateString()
/*     */   {
/* 131 */     if (this.suppressDate) {
/* 132 */       return null;
/*     */     }
/* 134 */     return new Date().toString();
/*     */   }
/*     */ 
/*     */   public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable)
/*     */   {
/* 140 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 142 */     innerClass.addJavaDocLine("/**");
/* 143 */     innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
/*     */ 
/* 146 */     sb.append(" * This class corresponds to the database table ");
/* 147 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 148 */     innerClass.addJavaDocLine(sb.toString());
/*     */ 
/* 150 */     addJavadocTag(innerClass, false);
/*     */ 
/* 152 */     innerClass.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addEnumComment(InnerEnum innerEnum, IntrospectedTable introspectedTable)
/*     */   {
/* 157 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 159 */     innerEnum.addJavaDocLine("/**");
/* 160 */     innerEnum.addJavaDocLine(" * This enum was generated by MyBatis Generator.");
/*     */ 
/* 163 */     sb.append(" * This enum corresponds to the database table ");
/* 164 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 165 */     innerEnum.addJavaDocLine(sb.toString());
/*     */ 
/* 167 */     addJavadocTag(innerEnum, false);
/*     */ 
/* 169 */     innerEnum.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn)
/*     */   {
/* 175 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 177 */     field.addJavaDocLine("/**");
/* 178 */     field.addJavaDocLine(" * This field was generated by MyBatis Generator.");
/*     */ 
/* 181 */     sb.append(" * This field corresponds to the database column ");
/* 182 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 183 */     sb.append('.');
/* 184 */     sb.append(introspectedColumn.getActualColumnName());
/* 185 */     field.addJavaDocLine(sb.toString());
/*     */ 
/* 187 */     addJavadocTag(field, false);
/*     */ 
/* 189 */     field.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addFieldComment(Field field, IntrospectedTable introspectedTable) {
/* 193 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 195 */     field.addJavaDocLine("/**");
/* 196 */     field.addJavaDocLine(" * This field was generated by MyBatis Generator.");
/*     */ 
/* 199 */     sb.append(" * This field corresponds to the database table ");
/* 200 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 201 */     field.addJavaDocLine(sb.toString());
/*     */ 
/* 203 */     addJavadocTag(field, false);
/*     */ 
/* 205 */     field.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addGeneralMethodComment(Method method, IntrospectedTable introspectedTable)
/*     */   {
/* 210 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 212 */     method.addJavaDocLine("/**");
/* 213 */     method.addJavaDocLine(" * This method was generated by MyBatis Generator.");
/*     */ 
/* 216 */     sb.append(" * This method corresponds to the database table ");
/* 217 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 218 */     method.addJavaDocLine(sb.toString());
/*     */ 
/* 220 */     addJavadocTag(method, false);
/*     */ 
/* 222 */     method.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addGetterComment(Method method, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn)
/*     */   {
/* 228 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 230 */     method.addJavaDocLine("/**");
/* 231 */     method.addJavaDocLine(" * This method was generated by MyBatis Generator.");
/*     */ 
/* 234 */     sb.append(" * This method returns the value of the database column ");
/* 235 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 236 */     sb.append('.');
/* 237 */     sb.append(introspectedColumn.getActualColumnName());
/* 238 */     method.addJavaDocLine(sb.toString());
/*     */ 
/* 240 */     method.addJavaDocLine(" *");
/*     */ 
/* 242 */     sb.setLength(0);
/* 243 */     sb.append(" * @return the value of ");
/* 244 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 245 */     sb.append('.');
/* 246 */     sb.append(introspectedColumn.getActualColumnName());
/* 247 */     method.addJavaDocLine(sb.toString());
/*     */ 
/* 249 */     addJavadocTag(method, false);
/*     */ 
/* 251 */     method.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addSetterComment(Method method, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn)
/*     */   {
/* 257 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 259 */     method.addJavaDocLine("/**");
/* 260 */     method.addJavaDocLine(" * This method was generated by MyBatis Generator.");
/*     */ 
/* 263 */     sb.append(" * This method sets the value of the database column ");
/* 264 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 265 */     sb.append('.');
/* 266 */     sb.append(introspectedColumn.getActualColumnName());
/* 267 */     method.addJavaDocLine(sb.toString());
/*     */ 
/* 269 */     method.addJavaDocLine(" *");
/*     */ 
/* 271 */     Parameter parm = (Parameter)method.getParameters().get(0);
/* 272 */     sb.setLength(0);
/* 273 */     sb.append(" * @param ");
/* 274 */     sb.append(parm.getName());
/* 275 */     sb.append(" the value for ");
/* 276 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 277 */     sb.append('.');
/* 278 */     sb.append(introspectedColumn.getActualColumnName());
/* 279 */     method.addJavaDocLine(sb.toString());
/*     */ 
/* 281 */     addJavadocTag(method, false);
/*     */ 
/* 283 */     method.addJavaDocLine(" */");
/*     */   }
/*     */ 
/*     */   public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable, boolean markAsDoNotDelete)
/*     */   {
/* 288 */     StringBuilder sb = new StringBuilder();
/*     */ 
/* 290 */     innerClass.addJavaDocLine("/**");
/* 291 */     innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
/*     */ 
/* 294 */     sb.append(" * This class corresponds to the database table ");
/* 295 */     sb.append(introspectedTable.getFullyQualifiedTable());
/* 296 */     innerClass.addJavaDocLine(sb.toString());
/*     */ 
/* 298 */     addJavadocTag(innerClass, markAsDoNotDelete);
/*     */ 
/* 300 */     innerClass.addJavaDocLine(" */");
/*     */   }
/*     */ }

/* Location:           C:\Users\sipingsoft-LILU.LJH\Desktop\mybatis-generator-core-1.3.0.jar
 * Qualified Name:     org.mybatis.generator.internal.DefaultCommentGenerator
 * JD-Core Version:    0.6.0
 */